### ISSUE TITLE
Extract Simulation Data and store it in Database

### ISSUE THREAD

**Issue by karimsiala** [openroboticmetaverse/mvp_mujoco_simulation#5]
## ✨ Desired Solution
Extract simulation data, inspect and filter relevant data, and store it in a database.

**📚 Technical Details**
- Use appropriate methods to extract data from the simulation instances.
- Inspect the data to determine its relevance and filter out unnecessary information.
- Check with Oussama on storing it in Database

**🚧 Challenges and Roadblocks**
- Filtering out unnecessary data while retaining relevant information.

**Subtasks**
- [ ] Extract data from a running MuJoCo 
- [ ] Inspect and filter relevant data (using Pandas for example).
- [ ] Set up a database for storing simulation data.
